### ISSUE TITLE
Populate missing fields in new Open States legislator records for 2023-2024 session

### ISSUE THREAD

**Issue by dscush** [ProgressiveMass/legislator-scorecard#101]
Similar to #90, there is plenty of data population work to do with the new session. We want this data to be manually entered into Open States so that our code doesn't need to automate a heuristics-based parsing of full names into first and last names, which is imperfect and risks culturally insensitive errors. We also want to fill in missing phone numbers and email addresses so that we can make it easy for our users to contact their legislators.

This work is complete when these legislators' Open States profiles (found in [this directory](https://github.com/openstates/people/tree/main/data/ma/legislature)) have been updated to include the indicated missing information. The fields are `givenName`, `familyName`, `email`, and `offices -> voice` - see [Jamie Eldridge](https://github.com/openstates/people/blob/main/data/ma/legislature/James-B-Eldridge-23704722-a50c-4148-8f14-98c7d78324b9.yml) for an example of a record with all these fields populated. So to be clear, this work will be done in the openstates/people repository, not here in the ProgressiveMass/legislator-scorecard repository. Our code consumes the data in that repository via API.

This is the output from the data build process indicating who needs which fields populated:

- No phone number for Paul W. Mark
- No phone number for Liz Miranda
- Robyn K. Kennedy missing givenName, using Robyn
- Robyn K. Kennedy missing familyName, using Kennedy
- Pavel M. Payano missing givenName, using Pavel
- Pavel M. Payano missing familyName, using Payano
- No phone number for Mindy Domb
- No phone number for Estela A. Reyes
- Estela A. Reyes missing givenName, using Estela
- Estela A. Reyes missing familyName, using Reyes
- No phone number for Ryan M. Hamilton
- Ryan M. Hamilton missing givenName, using Ryan
- Ryan M. Hamilton missing familyName, using Hamilton
- No phone number for Rodney M. Elliott
- Rodney M. Elliott missing givenName, using Rodney
- Rodney M. Elliott missing familyName, using Elliott
- No phone number for Kate Donaghue
- No phone number for Francisco E. Paulino
- Francisco E. Paulino missing givenName, using Francisco
- Francisco E. Paulino missing familyName, using Paulino
- No phone number for Manny Cruz
- No phone number for Margaret R. Scarsdale
- Margaret R. Scarsdale missing givenName, using Margaret
- Margaret R. Scarsdale missing familyName, using Scarsdale
- No phone number for Marcus S. Vaughn
- Marcus S. Vaughn missing givenName, using Marcus
- Marcus S. Vaughn missing familyName, using Vaughn
- No phone number for James C. Arena-DeRosa
- James C. Arena-DeRosa missing givenName, using James
- James C. Arena-DeRosa missing familyName, using Arena-DeRosa
- No phone number for Jennifer Balinsky Armini
- Jennifer Balinsky Armini missing givenName, using Jennifer
- Jennifer Balinsky Armini missing familyName, using Armini
- No phone number for Rita A. Mendes
- Rita A. Mendes missing givenName, using Rita
- Rita A. Mendes missing familyName, using Mendes
- No phone number for Christopher J. Worrell
- Christopher J. Worrell missing givenName, using Christopher
- Christopher J. Worrell missing familyName, using Worrell
- No email address for Kristin Kassner
- No phone number for Kristin Kassner
- No phone number for Samantha Montaño
- No phone number for Shirley B. Arriaga
- Shirley B. Arriaga missing givenName, using Shirley
- Shirley B. Arriaga missing familyName, using Arriaga
- No phone number for Christopher Richard Flanagan
- Christopher Richard Flanagan missing givenName, using Christopher
- Christopher Richard Flanagan missing familyName, using Flanagan
- No phone number for Dawne Shand
- No phone number for Simon Cataldo
- No phone number for Aaron L. Saunders
- Aaron L. Saunders missing givenName, using Aaron
- Aaron L. Saunders missing familyName, using Saunders
- No phone number for Judith A. Garcia
- Judith A. Garcia missing givenName, using Judith
- Judith A. Garcia missing familyName, using Garcia
- No email address for Priscila S. Sousa
- No phone number for Priscila S. Sousa
- Priscila S. Sousa missing givenName, using Priscila
- Priscila S. Sousa missing familyName, using Sousa
- No phone number for Adrianne Pasateri Ramos
- Adrianne Pasateri Ramos missing givenName, using Adrianne
- Adrianne Pasateri Ramos missing familyName, using Ramos

**Comment by akh4rf** [comment]
Updated list of missing info as of picking up ticket:

Robyn K. Kennedy missing givenName, using Robyn
Robyn K. Kennedy missing familyName, using Kennedy
Pavel M. Payano missing givenName, using Pavel
Pavel M. Payano missing familyName, using Payano
Estela A. Reyes missing givenName, using Estela
Estela A. Reyes missing familyName, using Reyes
Ryan M. Hamilton missing givenName, using Ryan
Ryan M. Hamilton missing familyName, using Hamilton
Rodney M. Elliott missing givenName, using Rodney
Rodney M. Elliott missing familyName, using Elliott
Francisco E. Paulino missing givenName, using Francisco
Francisco E. Paulino missing familyName, using Paulino
Margaret R. Scarsdale missing givenName, using Margaret
Margaret R. Scarsdale missing familyName, using Scarsdale
Marcus S. Vaughn missing givenName, using Marcus
Marcus S. Vaughn missing familyName, using Vaughn
James C. Arena-DeRosa missing givenName, using James
James C. Arena-DeRosa missing familyName, using Arena-DeRosa
Jennifer Balinsky Armini missing givenName, using Jennifer
Jennifer Balinsky Armini missing familyName, using Armini
Rita A. Mendes missing givenName, using Rita
Rita A. Mendes missing familyName, using Mendes
Christopher J. Worrell missing givenName, using Christopher
Christopher J. Worrell missing familyName, using Worrell
Shirley B. Arriaga missing givenName, using Shirley
Shirley B. Arriaga missing familyName, using Arriaga
Christopher Richard Flanagan missing givenName, using Christopher
Christopher Richard Flanagan missing familyName, using Flanagan
Aaron L. Saunders missing givenName, using Aaron
Aaron L. Saunders missing familyName, using Saunders
Judith A. Garcia missing givenName, using Judith
Judith A. Garcia missing familyName, using Garcia
No email address for Priscila S. Sousa
Priscila S. Sousa missing givenName, using Priscila
Priscila S. Sousa missing familyName, using Sousa
Adrianne Pusateri Ramos missing givenName, using Adrianne
Adrianne Pusateri Ramos missing familyName, using Ramos
