### ISSUE TITLE
Should we do anything about certain special cases?

### ISSUE THREAD

**Issue by JonathanCohn** [ProgressiveMass/legislator-scorecard#15]
People like Boncore, Brady, and O'Connor were not there the full session, so their scores aren't directly comparable to the others. And Stan Rosenberg rarely votes on things, thus bloating his score. Should we asterisk these somehow in the index? It's not a problem on their own pages.

**Comment by aholachek** [comment]
This was done:

<img width="1005" alt="Screen Shot 2019-04-10 at 9 15 53 AM" src="https://user-images.githubusercontent.com/3680488/55881757-42b37500-5b71-11e9-80c6-0b46d828f438.png">
