### ISSUE TITLE
Will the co-sponsorship stuff be "live"? 

### ISSUE THREAD

**Issue by JonathanCohn** [ProgressiveMass/legislator-scorecard#17]
If someone newly signs on to a bill, how do we get that updated here?

**Comment by aholachek** [comment]
HI @JonathanCohn (for some reason all your issues just popped up here for me right now, though I see you wrote them 3 days ago!)

My dream is to have my server directly pulling from Google spreadsheets via the api at least 1x a week, to ensure that @harmonywho or someone else can update the sheet and have it immediately go live.

This would require I think a fairly long sit down meeting where we finalize the exact spreadsheet templates that everyone promises to use going forward, to make it easy to automatically fetch & parse. 

For now, Harmony would have to update the spreadsheet she's sent to me and ask me to re-run my parsing script.

**Comment by JonathanCohn** [comment]
My account had been flagged (I had taken notes on a sheet of paper and then entered them all fairly rapidly--so it got caught up in spam), and I just fixed that this morning. 

Thanks!

There were some recent cosoponsorships not on the site. Is syncing the Excel sheet the easiest way to go about updating that? cc: @harmonywho

**Comment by harmonywho** [comment]
I'm trying to find the email I thought I wrote this morning from my iphone, i thought it would magically appear here. It ididn't! Adn I can't find it! maybe I never sent it. 

But here's the suggestion/ I think JC agreed (so it wasn't imaginary): 
- [ ] We, PMIC, JC, Me, etc, should MIGRATE our work and updates over to the sheet Alex has been working from. This will take some cross checking to remerge some stuff that had divorced at a certain point (SORRY)

But this makes the most sense. 

- [ ] Alex should advise us which TABS and CELLS absolutely need to stay as is/are. 
We will be religious in adhering. 

- [ ] And we PM/IC should restrict who has access to editing etc. and have "rules" somewhere on another tab explaining protocols and access for our various vols and point ppl now and into the future. (if JC and I get hit by a truck and Alex finds Luddism attractive when she goes to NJ... someone would have the basics of the operation as a schematic to work from) 

Does this make sense? 

@aholachek , and you do an accounting / list of exactly which spreadsheets you're using (w/ the links please?) and which tabs, to start? 

Longer sit down / in person we can go over DONT TOUCH THIS , DONT ADD THAT kind of stuff. We'll not do anything extra adding -- just changing vote content, the like, -- for now. 

Yeah?
