### ISSUE TITLE
Minor text edits to Agenda bill language 

### ISSUE THREAD

**Issue by JonathanCohn** [ProgressiveMass/legislator-scorecard#20]
Upgrades state’s zoning laws to encourage more affordable housing and transit-oriented, walkable development, and promotes inclusionary zoning practices.

Swap these in for the text in the respective places. Thanks!

Eliminates or reduces numerous fees, such as parole supervision, and ensures indigent residents are not jailed or given unreasonable fees simply because they struggle to pay court-related fines.

Modernizes voter registration by automatically registering citizens who interact with government agencies ("opt-out" instead of "opt-in") and ensures that such information is handled in a secure fashion.

Holds gas companies to a high standard with regards to new infrastructure and prevents massive public subsidy of new interstate gas pipelines.

**Comment by aholachek** [comment]
hi @JonathanCohn do you have access to the spreadsheet @harmonywho has shared with me with the cosponsor data?

If not, do you think you could get her to share it with you so that you can directly edit the descriptions in the cells and then tell me to re-run my scripts? I'd like to keep the spreadsheets as the "single source of truth" so that updates don't get wiped when I rerun the parsing scripts.

**Comment by harmonywho** [comment]
Right right now we have dual sources. Should we migrate over to Alex's and
make that the Home?

--
Harmony Wu
Board Member,
Progressive Mass

**Comment by JonathanCohn** [comment]
Yeah, that makes sense. Harmony, send me over what you're working on, so I
can edit there. Or if it's a different tab on the same sheet, just let me
know.

**Comment by harmonywho** [comment]
I think what we need to do is have Alex precisely enumerate each of her
source tabs, and then we can hand curate, update votes etc.

Just fyi Jonathan, one thing we on this side have to be careful of is the
legislator NAMES need to be very precisely matched with database, so pretty
much leave the name columns as is

--
Harmony Wu
Board Member,
Progressive Mass
