### ISSUE TITLE
RELEASE DATE: Queries, Discussion

### ISSUE THREAD

**Issue by harmonywho** [ProgressiveMass/legislator-scorecard#25]
_When? What Needs to Be Done before? (bigger pic todos, vs tweaks and updates)_
**With Alex**
- [ ] Hosting, URL, etc stuff (can we figure out a way to have it live on progressivemass.com? (tho not in the ugly old needs-to-be-updated Nationbuilder!)
- [ ] Hosting $$: the faster thingy, $7? etc. Limitations of, how to manage, etc. 
- [ ] Admin and upkeep of existing and future? (How do we get up to speed and maintain and do best prax... what if you're on vacation? etc) 

**PMIC Stuff**
- [ ] Press Release
- [ ] (Some) Overhaul of evergreen/existing webpage language to frame the new site (not sure what things would need to change, but not sure what?)
- [ ] EXCITING LANGUAGE/ANNOUNCEMENT about our new Scorecard!!! Emphasizing our themes, education and how data can be used etc (maybe multiple parts here, this is just brainstorm) 

(I dont know that PMIC is in this space, but dumping here for u, Alex, to have  sense of what is happening on the other side, and to record/list the outstanding questions)

**Comment by aholachek** [comment]
@harmonywho I sent you an email about this witha brief discussion of what we might want to do for using the progressivemass domain
