### ISSUE TITLE
"Support Our Work"

### ISSUE THREAD

**Issue by harmonywho** [ProgressiveMass/legislator-scorecard#8]
One of the best things we do, made even better-er by your work and presentation -- we would be negligent if we didn't ask for $$$ support and community sign up from this. 

(I hope that doesnt seem crude, it's just the damned facts -- Soros ain't ponying up yet and maybe we don't need him if the People all chip in!) 

It should be visible and persistent (ie, there's an ask on every view, unless otherwise unreasonable/imposs). 

Something like: "PM and the Scorecard are result of hard work, lots of RESEARCH, TIME and EFFORT and CODING and AWESOME things. Show your support with a contribution..."

**Comment by aholachek** [comment]
<img width="1100" alt="screen shot 2017-03-30 at 7 14 30 pm" src="https://cloud.githubusercontent.com/assets/3680488/24530014/328c3310-157d-11e7-990d-393e6801d8cb.png">
Something like this?

**Comment by harmonywho** [comment]
Yeah, something like that! Maybe some language tweaking? When we get to polishing? But yes.

**Comment by aholachek** [comment]
this was done
