### ISSUE TITLE
Utilize given_name and family_name in Open States data, if available

### ISSUE THREAD

**Issue by dscush** [ProgressiveMass/legislator-scorecard#85]
Rep Brandy Fluker Oakley's surname is "Fluker Oakley" but the scorecard code only looks at the `name` field from Open States which is "Brandy Fluker Oakley" and then assumes "Fluker" is her middle name and "Oakley" is her last name. I added `given_name: Brandy` and `family_name: Fluker Oakley` to her Open States record (https://github.com/openstates/people/pull/710) so now if we update our code to utilize those fields when present, we can properly display her surname. We should first check if `given_name` and `family_name` are present on the record and continue our current parsing of `name` for records where they're absent/unpopulated.

**Comment by JonathanCohn** [comment]
Any update on this? Would a temporary workaround on our end be to pull in the middle name field?

**Comment by dscush** [comment]
I'm planning to work on this one this week. I don't expect it to be too difficult.

**Comment by JonathanCohn** [comment]
Thanks!

**Comment by dscush** [comment]
Done!
