### ISSUE TITLE
Add missing givenName and familyName for legislators in OpenStates

### ISSUE THREAD

**Issue by dscush** [ProgressiveMass/legislator-scorecard#90]
The following 36 legislators have neither `givenName` nor `familyName` populated in their Open States profiles:

- Rebecca L. Rausch
- Joanne M. Comerford 
- Barry R. Finegold 
- Edward J. Kennedy 
- Susan L. Moran 
- David Allen Robertson
- Lindsay N. Sabadosa 
- Nika C. Elugardo 
- Tami L. Gouveia
- David Henry Argosky LeBoeuf 
- Daniel R. Carey 
- Marcos A. Devers 
- Michael J. Soter 
- Maria Duaime Robinson
- Natalie M. Blais 
- Patrick Joseph Kearney
- Norman J. Orrall 
- Christina A. Minicucci 
- Tram T. Nguyen 
- Richard M. Haggerty 
- Kathleen R. LaNatra 
- Michelle L. Ciccolo 
- Alyson M. Sullivan 
- Carol A. Doherty 
- Jessica Ann Giannino
- Edward R. Philips 
- Kip A. Diggs 
- Danillo A. Sena 
- Jacob R. Oliveira 
- Steven G. Xiarhos 
- Michael P. Kushmerek 
- Patricia A. Duffy 
- Sally P. Kerans 
- Adam J. Scanlon 
- Kelly W. Pease 
- Steven C. Owens 

We want this data to be manually entered into Open States so that our code doesn't need to automate a heuristics-based parsing of full names into first and last names, which is imperfect and risks culturally insensitive errors.

This work is complete when these legislators' Open States profiles (found in [this directory](https://github.com/openstates/people/tree/main/data/ma/legislature)) have been updated to include the `givenName` and `familyName` fields. So to be clear, this work will be done in the `openstates/people` repository, not here in the `ProgressiveMass/legislator-scorecard` repository. Our code consumes the data in that repository via API.

**Comment by ascampos** [comment]
PR has been merged to `openstates/people` https://github.com/openstates/people/pull/876

**Comment by dscush** [comment]
Thanks @ascampos!
